#!/usr/bin/env ruby
# Inspired by sensu-community-plugins:network/metrics-net.rb

require_relative '../base'

#
# Fetch interface counter information from the /sys filesystem
# (tx/rx packets, bytes and errors)
#
# Accepts a graphite prefix
#
class InterfaceCounterMetrics < Metric::Graphite
  option :prefix, short: '-p <prefix>',
                  description: 'Graphite prefix/path. See README',
                  default: '%h.net.iface'

  def run
    @timestamp = Time.now.to_i
    @stats = %i(tx_packets rx_packets tx_bytes rx_bytes tx_errors rx_errors)

    Dir.glob('/sys/class/net/*').each do |iface_path|
      next if File.file?(iface_path)
      iface = File.basename(iface_path)

      read_interface(iface_path, iface)
    end
    ok
  end

  private

  def read_interface(iface_path, iface)
    @stats.each do |stat|
      value = File.open("#{iface_path}/statistics/#{stat}").read.strip
      output "#{prefix}.#{iface}.#{stat}", value, @timestamp
    end

    value = File.open("#{iface_path}/operstate").read.strip
    output "#{prefix}.#{iface}.state", value, @timestamp
  end
end
