#!/usr/local/rvm/wrappers/default/ruby

require 'json'
require_relative '../base'

# If the state of any defined replication service is one we don't
# like the look of - go into a given state
class CheckTungstenState < Check
  check_name 'Tungsten Replication State'

  def run
    failures = []
    failtype = nil

    data = JSON.parse(`sudo /opt/continuent/tungsten/tungsten-replicator/bin/trepctl services -json`)
    data.each do |service|
      if (failure = states[service['state']])
        failures << service['serviceName']
        failtype = failure unless failtype == :critical
      end
    end

    handle(failtype, failures)
  end

  private

  def handle(failtype, failures)
    if failtype
      send(failtype, failures.join(', '))
    else
      ok 'All services healthy'
    end
  end

  def states
    # Any state which should return a status other than 'ok', and its exit type
    # http://docs.continuent.com/tungsten-replicator-2.2/operations-status-states.html
    {
      'OFFLINE:ERROR' => :critical
    }
  end
end
