#!/usr/local/rvm/wrappers/default/ruby

require 'json'
require_relative '../base'

# Record some metrics about the state of each defined service
# (as defined in #fields)
class TungstenMetrics < Metric::Graphite
  option :prefix, short: '-p <prefix>',
                  description: 'Graphite prefix/path. See README',
                  default: '%h.replicator'

  def run
    # Tungsten helpfully prints ... while it is waiting. That's not valid json
    data = `sudo /opt/continuent/tungsten/tungsten-replicator/bin/trepctl services -json -full`
    data.gsub!(/^\.+/, '')
    data = JSON.parse(data)

    data.each do |service|
      metrics = service.select { |m| fields.include?(m) }
      name = service['clusterName']
      metrics.each do |metric, value|
        output "#{prefix}.#{name}.#{metric}", value, timestamp
      end
    end

    ok
  end

  private

  def fields
    %w(appliedLastSeqno appliedLatency latestEpochNumber
       maximumStoredSeqNo minimumStoredSeqNo relativeLatency
       state timeInStateSeconds uptimeSeconds)
  end
end
