#!/usr/local/rvm/wrappers/default/ruby

require_relative '../base'
require 'uri'
require 'net/http'

class CheckAPI < Check
  check_name 'Check API'

  option :uri,
         short: '-u <uri>',
         description: 'URI of the API server',
         required: true

  def run
    response = fetch

    case response.code.to_i
    when 200..204 then ok "v#{response['X-Spark-Version']}"
    else critical "#{response.code} #{response.message}"
    end
  rescue => exception
    critical "#{exception.class}: #{exception.message}"
  end

  private

  def fetch(uri = "#{config[:uri]}/server.json")
    uri = URI.parse(uri)
    request = Net::HTTP.new(uri.host, uri.port)
    request.use_ssl = (uri.scheme == 'https')

    request.head(uri.request_uri)
  end
end
