#!/usr/local/rvm/wrappers/default/ruby

require_relative '../base'

class CheckOmrelp < Check
  check_name 'Check OMRELP connected'

  def run
    stdout = `netstat -4tnw | grep 514`

    connections = parse_netstat(stdout)

    rsyslog_connection = connections.find { |c| c[:remote_port] == '514' }

    return critical 'No omrelp connection' if rsyslog_connection.nil?
    return ok if rsyslog_connection[:state] == 'ESTABLISHED'

    warning "omrelp connection state: #{rsyslog_connection[:state]}"
  end

  def parse_netstat(stdout)
    stdout.split("\n").map do |line|
      parse_netstat_line(line)
    end
  end

  def parse_netstat_line(line)
    proto, recvq, sendq, local_addr, remote_addr, state = line.split(' ')

    local_addr, local_port = separate_port(local_addr)
    remote_addr, remote_port = separate_port(remote_addr)

    {
      proto: proto,
      recvq: recvq,
      sendq: sendq,
      local_addr: local_addr,
      local_port: local_port,
      remote_addr: remote_addr,
      remote_port: remote_port,
      state: state
    }
  end

  def separate_port(addr_and_port)
    return [] unless addr_and_port
    addr_and_port.split(':')
  end
end
